config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :rooms do
    resources :messages
  end
  root 'rooms#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room

  validates  :text, presence: true
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages, dependent: :destroy
  belongs_to :user

  validates  :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :rooms, dependent: :destroy
  has_many :messages, dependent: :destroy

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }

  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password, :avatar) }
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :authenticate_user!

  def index
    @room = Room.find(params[:room_id])
    @messages = @room.messages.all
    @message = Message.new
  end

  def create
    @room = Room.find(params[:room_id])
    message = @room.messages.new(message_params)
    message.user_id = current_user.id
    message.save
    redirect_to room_messages_path(@room)
    flash[:success] = "Message successfully created"
  end

  def edit
    @room = Room.find(params[:room_id])
    @message = @room.messages.find(params[:id])
  end

  def update
    @room = Room.find(params[:room_id])
    message = @room.messages.find(params[:id])
    message.update(message_params)
    redirect_to room_messages_path(@room)
    flash[:success] = "Message successfully updated"
  end

  def destroy
    @room = Room.find(params[:room_id])
    message = @room.messages.find(params[:id])
    message.destroy
    redirect_to room_messages_path(@room)
  end

  private

  def message_params
    params.require(:message).permit(:text)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_room, only: [:edit, :update, :destroy]

  def index
    @room = Room.new
    @rooms = Room.order("created_at DESC")
  end

  def create
    @room = current_user.rooms.create(room_params)
    redirect_to root_path
    flash[:success] = "Room successfully created"
  end

  def edit
  end

  def update
    @room.update(room_params)
    redirect_to root_path
    flash[:success] = "Room successfully created"
  end

  def destroy
    @room.destroy
    redirect_to root_path
  end

  private

  def set_room
    @room = Room.find(params[:id])
  end

  def room_params
    params.require(:room).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def bootstrap_flash_class(flash_type)
    { success: 'alert-success',
      error:   'alert-danger',
      alert:   'alert-warning',
      notice:  'alert-info'
    }[flash_type.to_sym] || flash_type.to_s
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/layouts/_flash.html.erb
<% flash.each do |type, message| %>
    <div class="alert <%= bootstrap_flash_class(type) %> fade in">
      <button class="close" data-dismiss="alert">×</button>
      <%= message %>
    </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Applikey</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="container-fluid">
    <div class="header">
      <nav class="navbar navbar-light header" style="background-color: #3b88b9;">
        <% if user_signed_in? %>
            <%= link_to 'Log Out', destroy_user_session_path, method: :delete, class: "logout_header" %>
        <% end %>
        <% if current_user && current_user.avatar? %>
            <div class="round-image-50 in-header"><%= image_tag(current_user.avatar.url(:thumb)) %></div>
        <% elsif current_user && current_user.avatar? == false %>
            <div class="round-image-50 in-header"><%= image_tag("no-avatar.jpg") %></div>
        <% end %>
        <% if /\/$/.match request.original_url %>
            <h3 class="text_header">Chat - Rooms</h3>
        <% elsif /messages$/.match request.original_url %>
            <h3 class="text_header">Messages</h3>
        <% end %>
      </nav>
    </div>
    <%= render 'layouts/flash' %>
    <%= yield %>
  </div>
  </body>
</html>

app/views/messages/_new.html.erb
<%= simple_form_for [@room, @message] do |f| %>
    <%= f.input :text %>
    <%= f.button :submit %>
<% end %>

app/views/messages/edit.html.erb
<div class="back">
  <%= link_to "<< Back", room_messages_path(@room)  %>
</div>
<h2 class="text-center">Edit message</h2>
<div class="edit-room">
  <%= render 'messages/new'%>
</div>

app/views/messages/index.html.erb
<div class="nav-links">
  <div class="back">
    <%= link_to "<< Back", root_path  %>
  </div>
  <div class="message-header">
    <h2 class="text-center"> <%= @room.name %> room</h2>
  </div>
</div>

<div class="half">
  <% if @messages.count == 0 %>
      <h3 class="text-center">Page is empty</h3>
  <% end %>

  <% @messages.each do |message| %>
      <div class="room-container well">
        <% if message.user.avatar? %>
            <div class="round-image-50 in-message"><%= image_tag(message.user.avatar.url(:thumb)) %></div>
        <% else %>
            <div class="round-image-50 in-message"><%= image_tag("no-avatar.jpg") %></div>
      <% end %>
        <div class="room-info">
          <div class="room-name">
            <h4><%= message.text %></h4>
          </div>
          <div class="room-creator">
            <span>Created by: <%= message.user.email %></span>
          </div>
          <div class="room-date">
            <%= message.created_at.to_date %>
          </div>
        </div>
        <% if current_user && current_user.id == message.user.id  %>
            <div class="room-links">
              <div class="room-link">
                <%= link_to "Edit", edit_room_message_path(@room, message)  %>
              </div>
              <div class="room-link">
                <%= link_to "Delete", [@room, message], method: :delete, remote: true, class: "delete-link" %>
              </div>
            </div>
        <% end %>
      </div>
  <% end %>
</div>

<div class="new-message well">
  <%= render 'messages/new'%>
</div>

app/views/rooms/_new.html.erb
<%= simple_form_for @room do |f| %>
    <%= f.input :name %>
    <%= f.button :submit %>
<% end %>

app/views/rooms/edit.html.erb
<div class="back">
  <%= link_to "<< Back", root_path  %>
</div>

<h2 class="text-center">Edit room</h2>

<div class="edit-room">
  <%= render 'rooms/new'%>
</div>

app/views/rooms/index.html.erb
<div class="edit-user">
  <h5>  <%= button_to "Edit User", edit_user_registration_path, method: :get, class: "btn btn-success"  %></h5>
</div>

<div class="half">
  <% if @rooms.count == 0 %>
  <h3 class="text-center">Page is empty</h3>
  <% end %>

<% @rooms.each do |room| %>
        <div class="room-container well">
          <% if room.user.avatar? %>
              <div class="round-image-50 in-message"><%= image_tag(room.user.avatar.url(:thumb)) %></div>
          <% else %>
              <div class="round-image-50 in-message"><%= image_tag("no-avatar.jpg") %></div>
          <% end %>
          <div class="room-info">
            <div class="room-name">
              <h4> <%= link_to room.name, room_messages_path(room) %></h4>
            </div>
            <div class="room-creator">
              <span>Created by: <%= room.user.email %></span>
            </div>
            <div class="room-date">
              <%= room.created_at.to_date %>
            </div>
          </div>
          <% if current_user && current_user.id == room.user.id  %>
              <div class="room-links">
                <div class="room-link">
                  <%= link_to "Edit", edit_room_path(room) %>
                </div>
                <div class="room-link">
                  <%= link_to "Delete", room, method: :delete, remote: true, class: "delete-link" %>
                </div>
              </div>
          <% end %>
        </div>
  <% end %>
</div>

<div class="new-room well">
  <%= render 'rooms/new'%>
</div>